collections:
    games_index:
        output: true
        permalink: /games/:name/index.html
    games_play:
        output: true
        permalink: /games/:name/play.html

defaults:
  - scope:
      path: ""
      type: "games_index"
    values:
      layout: "games_index"
      author: "Adri"
  - scope:
      path: ""
      type: "games_play"
    values:
      layout: "games_play"
      author: "Adri"
